import type { DualText, Wonders } from "@/types";

import contentJson from "./countryContent.json";

/**
 * Guardian-approved Country content — the shippable output of the authoring
 * pipeline (ADR-0002). GENERATED by `npm run author:content` from
 * `src/data/countryDrafts.ts`; do not hand-edit. The app imports this plain
 * data only, so the Content Guardian never ships in the live bundle.
 *
 * `contentPipeline.test.ts` asserts this file matches the pipeline output.
 */
export interface CountryContent {
  wonders: Wonders;
  flagMeaning: DualText;
}

export const COUNTRY_CONTENT = contentJson as unknown as Record<string, CountryContent>;
