import type { WonderPhoto } from "@/lib/wikimedia";
import manifest from "./wonderPhotos.json";

/**
 * Attribution manifest for the committed **Wonder** photos (ADR-0007), keyed by
 * `<code>-<slot>` (e.g. "fra-landmark"). GENERATED by
 * `npm run gen:wonder-photos`; the images themselves live in `public/wonders`.
 *
 * Empty until photos are sourced — the Wonders station then shows the emoji
 * fallback, so coverage and pictures land independently (as in ADR-0004).
 */
const PHOTOS = manifest as Record<string, WonderPhoto>;

/** The committed photo for a Wonder, or undefined (→ emoji fallback). */
export function getWonderPhoto(code: string, slot: string): WonderPhoto | undefined {
  return PHOTOS[`${code.toLowerCase()}-${slot}`];
}

/** How many Wonder photos are committed (for the contact sheet / status). */
export const WONDER_PHOTO_COUNT = Object.keys(PHOTOS).length;
